import type { Metadata } from "next";
import { Sen } from "next/font/google";
import "./globals.css";
import  Header  from '../components/Header'
import  Footer  from '../components/Footer'
import {ThemeProvider} from '../components/ThemeProvider'

const josef = Sen({ subsets: ["latin"] ,
  weight: ['400' , '500' , '600' , '700'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Interior Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={josef.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <Header />
        {children}
        <Footer />
      </ThemeProvider>
      </body>
    </html>
  );
}
